create table if not exists return_codes (
  id uuid primary key default gen_random_uuid(),
  code text unique not null,
  customer_name text,
  customer_email text,
  customer_phone text,
  original_order_id uuid,
  original_tracking_number text,
  note text,
  is_used boolean default false,
  used_at timestamptz,
  created_at timestamptz default now()
);
create table if not exists return_requests (
  id uuid primary key default gen_random_uuid(),
  access_code text,
  customer_name text,
  customer_email text,
  customer_phone text,
  original_order_id uuid,
  original_tracking_number text,
  reason text,
  comments text,
  address_line1 text,
  address_line2 text,
  city text,
  state text,
  zip text,
  country text default 'US',
  return_address text,
  parcel_length numeric default 13,
  parcel_width numeric default 10,
  parcel_height numeric default 10,
  parcel_weight_lb numeric default 1,
  parcel_weight_oz numeric default 0,
  status text default 'requested',
  easypost_shipment_id text,
  return_tracking_number text,
  return_tracking_url text,
  return_label_url text,
  return_carrier text,
  return_service text,
  return_postage_amount numeric,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);
